version: "3.8"
services:
  backend:
    build:
      context: ./FlashMindAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flash_mind_api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./FlashMindClient
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  db:
    image: postgres:15
    container_name: postgres_flashmind
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flash_mind_api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
